import type { Lang } from "@/lib/site-data";

type ChatCopy = { launcher:string; close:string; status:string; eyebrow:string; title:string; intro:string; name:string; email:string; company:string; country:string; question:string; questionHint:string; start:string; starting:string; privacy:string; welcome:string; closed:string; message:string; send:string; unavailable:string; failed:string };
export const chatCopy: Record<Lang, ChatCopy> = {
  en:{launcher:"Chat with sales",close:"Close",status:"Leave a message anytime",eyebrow:"Talk to our factory sales team",title:"How can we help?",intro:"Tell us what you are sourcing. Your conversation stays available on this device.",name:"Name",email:"Business email",company:"Company",country:"Country",question:"Your question",questionHint:"Product model, target market, quantity or customization needs…",start:"Start conversation",starting:"Starting…",privacy:"We normally reply by chat or email. Do not send sensitive payment information.",welcome:"Ask us about products, OEM/ODM, samples or accessories.",closed:"This conversation has ended. Use the quotation form for a new request.",message:"Type your message…",send:"Send message",unavailable:"Unable to start chat.",failed:"Message could not be sent."},
  es:{launcher:"Hablar con ventas",close:"Cerrar",status:"Déjenos un mensaje cuando quiera",eyebrow:"Hable con nuestro equipo comercial",title:"¿Cómo podemos ayudarle?",intro:"Cuéntenos qué producto busca. La conversación seguirá disponible en este dispositivo.",name:"Nombre",email:"Correo empresarial",company:"Empresa",country:"País",question:"Su consulta",questionHint:"Modelo, mercado, cantidad o personalización…",start:"Iniciar conversación",starting:"Iniciando…",privacy:"Respondemos por chat o correo. No envíe información de pago confidencial.",welcome:"Consúltenos sobre productos, OEM/ODM, muestras o accesorios.",closed:"Esta conversación ha finalizado. Use el formulario de cotización para una nueva solicitud.",message:"Escriba su mensaje…",send:"Enviar mensaje",unavailable:"No se pudo iniciar el chat.",failed:"No se pudo enviar el mensaje."},
  pt:{launcher:"Falar com vendas",close:"Fechar",status:"Deixe uma mensagem a qualquer momento",eyebrow:"Fale com a nossa equipa comercial",title:"Como podemos ajudar?",intro:"Conte-nos o que procura. A conversa continuará disponível neste dispositivo.",name:"Nome",email:"E-mail empresarial",company:"Empresa",country:"País",question:"A sua pergunta",questionHint:"Modelo, mercado, quantidade ou personalização…",start:"Iniciar conversa",starting:"A iniciar…",privacy:"Respondemos por chat ou e-mail. Não envie dados de pagamento confidenciais.",welcome:"Pergunte sobre produtos, OEM/ODM, amostras ou acessórios.",closed:"Esta conversa terminou. Use o formulário de cotação para um novo pedido.",message:"Escreva a sua mensagem…",send:"Enviar mensagem",unavailable:"Não foi possível iniciar o chat.",failed:"Não foi possível enviar a mensagem."},
  fr:{launcher:"Contacter les ventes",close:"Fermer",status:"Laissez-nous un message à tout moment",eyebrow:"Échangez avec notre équipe commerciale",title:"Comment pouvons-nous vous aider ?",intro:"Décrivez votre recherche. La conversation restera disponible sur cet appareil.",name:"Nom",email:"E-mail professionnel",company:"Entreprise",country:"Pays",question:"Votre question",questionHint:"Modèle, marché, quantité ou personnalisation…",start:"Démarrer la conversation",starting:"Démarrage…",privacy:"Nous répondons par chat ou e-mail. N’envoyez aucune donnée de paiement sensible.",welcome:"Posez vos questions sur les produits, l’OEM/ODM, les échantillons ou les accessoires.",closed:"Cette conversation est terminée. Utilisez le formulaire de devis pour une nouvelle demande.",message:"Écrivez votre message…",send:"Envoyer le message",unavailable:"Impossible de démarrer le chat.",failed:"Impossible d’envoyer le message."},
  ar:{launcher:"تحدث مع المبيعات",close:"إغلاق",status:"اترك رسالة في أي وقت",eyebrow:"تحدث مع فريق مبيعات المصنع",title:"كيف يمكننا مساعدتك؟",intro:"أخبرنا بما تبحث عنه. ستبقى المحادثة متاحة على هذا الجهاز.",name:"الاسم",email:"البريد الإلكتروني للعمل",company:"الشركة",country:"الدولة",question:"سؤالك",questionHint:"الموديل أو السوق أو الكمية أو متطلبات التخصيص…",start:"بدء المحادثة",starting:"جارٍ البدء…",privacy:"نرد عبر الدردشة أو البريد الإلكتروني. لا ترسل بيانات دفع حساسة.",welcome:"اسألنا عن المنتجات أو OEM/ODM أو العينات أو الملحقات.",closed:"انتهت هذه المحادثة. استخدم نموذج طلب عرض السعر لطلب جديد.",message:"اكتب رسالتك…",send:"إرسال الرسالة",unavailable:"تعذر بدء المحادثة.",failed:"تعذر إرسال الرسالة."},
  zh:{launcher:"联系销售",close:"关闭",status:"可随时留言",eyebrow:"联系工厂销售团队",title:"我们能为您做什么？",intro:"请告诉我们您的采购需求。本设备会保留此次聊天记录。",name:"姓名",email:"企业邮箱",company:"公司",country:"国家或地区",question:"您的问题",questionHint:"产品型号、目标市场、数量或定制需求……",start:"开始聊天",starting:"正在建立会话……",privacy:"我们会通过聊天或邮件回复，请勿发送敏感付款信息。",welcome:"您可以咨询产品、OEM/ODM、样品或配件。",closed:"本次会话已结束。如有新需求，请使用询盘表单。",message:"输入消息……",send:"发送消息",unavailable:"暂时无法开始聊天。",failed:"消息发送失败。"},
  ru:{launcher:"Связаться с отделом продаж",close:"Закрыть",status:"Оставьте сообщение в любое время",eyebrow:"Свяжитесь с отделом продаж завода",title:"Чем мы можем помочь?",intro:"Расскажите, что вы ищете. Переписка сохранится на этом устройстве.",name:"Имя",email:"Рабочая эл. почта",company:"Компания",country:"Страна",question:"Ваш вопрос",questionHint:"Модель, рынок, количество или требования к персонализации…",start:"Начать разговор",starting:"Подключение…",privacy:"Мы ответим в чате или по почте. Не отправляйте конфиденциальные платёжные данные.",welcome:"Спросите нас о продукции, OEM/ODM, образцах или аксессуарах.",closed:"Разговор завершён. Для нового запроса используйте форму заявки.",message:"Введите сообщение…",send:"Отправить",unavailable:"Не удалось начать разговор.",failed:"Не удалось отправить сообщение."},
};
