"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { Edit3, ExternalLink, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";

type Media = { id: string; type: "IMAGE" | "VIDEO"; originalName: string; publicUrl?: string | null };
type Product = { id: string; model: string };
type VideoItem = { id: string; slug: string; title: string; description: string; category: string; status: string; videoId: string; posterId?: string | null; productId?: string | null; sortOrder: number; videoUrl?: string | null; posterUrl?: string | null; productModel: string };
const categoryLabels: Record<string, string> = { PRODUCT_OPERATION: "产品操作视频", EXTRACTION_ANIMATION: "萃取流程动画", FACTORY: "工厂视频" };
const statusLabels: Record<string, string> = { DRAFT: "草稿", PUBLISHED: "已发布", ARCHIVED: "已归档" };
const empty: VideoItem = { id: "", slug: "", title: "", description: "", category: "PRODUCT_OPERATION", status: "DRAFT", videoId: "", posterId: null, productId: null, sortOrder: 0, productModel: "" };

export function VideoWorkspace() {
  const [items, setItems] = useState<VideoItem[]>([]); const [media, setMedia] = useState<Media[]>([]); const [products, setProducts] = useState<Product[]>([]);
  const [editing, setEditing] = useState<VideoItem | null>(null); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const apply = (body: { items?: VideoItem[]; media?: Media[]; products?: Product[] }) => { setItems(body.items || []); setMedia(body.media || []); setProducts(body.products || []); };
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/videos", { cache: "no-store" }); const body = await response.json(); if (response.ok) apply(body); else setMessage(body.error || "视频数据加载失败。"); setLoading(false); }, []);
  useEffect(() => { const controller = new AbortController(); fetch("/api/admin/videos", { cache: "no-store", signal: controller.signal }).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (!response.ok) throw new Error(body.error || "视频数据加载失败。"); apply(body); }).catch((error: unknown) => { if (error instanceof Error && error.name !== "AbortError") setMessage(error.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  const filtered = useMemo(() => { const term = query.toLowerCase(); return items.filter((item) => `${item.title} ${item.slug} ${item.productModel}`.toLowerCase().includes(term)); }, [items, query]);
  const videos = media.filter((item) => item.type === "VIDEO"); const images = media.filter((item) => item.type === "IMAGE");
  async function save(event: React.FormEvent) { event.preventDefault(); if (!editing) return; setSaving(true); setMessage(""); const response = await fetch("/api/admin/videos", { method: editing.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); const body = await response.json(); setSaving(false); if (!response.ok) return setMessage(body.error || "保存失败。"); setEditing(null); setMessage("视频记录已保存。"); await load(); }
  async function remove(item: VideoItem) { if (!window.confirm("确认删除这条视频记录？媒体库中的原文件不会被删除。")) return; const response = await fetch("/api/admin/videos", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error || "删除失败。"); setMessage("视频记录已删除，原文件仍保留在媒体库。"); await load(); }
  const change = (key: keyof VideoItem, value: string | number | null) => editing && setEditing({ ...editing, [key]: value });

  return <section className="video-workspace cms-manager"><header className="cms-page-heading"><div><span>视频资源</span><h1>视频管理</h1><p>从媒体库关联真实视频、封面与产品，并控制排序和发布状态。</p></div><button className="cms-primary" onClick={() => setEditing({ ...empty })}><Plus size={17}/>新增视频记录</button></header>
    {!videos.length ? <p className="cms-notice">媒体库中还没有视频。请先进入“媒体资源”上传 MP4 或 WebM 文件，再返回创建视频记录。</p> : null}
    <div className="cms-toolbar"><label><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索视频标题、路径或产品型号" /></label><button onClick={() => void load()} disabled={loading}><RefreshCw size={16}/>{loading ? "加载中…" : "刷新"}</button><span>共 {filtered.length} 条</span></div>{message ? <p className="cms-notice" role="status">{message}</p> : null}
    <div className="cms-video-grid">{filtered.map((item) => <article className="cms-video-card" key={item.id}><div className="cms-video-frame">{item.posterUrl ? <Image unoptimized src={item.posterUrl} alt="" fill sizes="420px"/> : item.videoUrl ? <video src={item.videoUrl} muted preload="metadata"/> : <span>无预览</span>}</div><div><span className={`cms-status is-${item.status.toLowerCase()}`}>{statusLabels[item.status]}</span><h2>{item.title}</h2><p>{categoryLabels[item.category]}{item.productModel ? ` · ${item.productModel}` : ""}</p><small>/{item.slug} · 排序 {item.sortOrder}</small></div><div className="cms-actions">{item.videoUrl ? <a href={item.videoUrl} target="_blank" rel="noreferrer" aria-label="播放源文件"><ExternalLink size={16}/></a> : null}<button aria-label="编辑" onClick={() => setEditing(item)}><Edit3 size={16}/></button><button className="is-danger" aria-label="删除" onClick={() => void remove(item)}><Trash2 size={16}/></button></div></article>)}</div>
    {!loading && !filtered.length ? <div className="cms-empty">暂无视频记录。</div> : null}
    {editing ? <div className="cms-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(null); }}><form className="cms-modal" onSubmit={save}><header><div><span>{editing.id ? "编辑" : "新增"}</span><h2>视频记录</h2></div><button type="button" onClick={() => setEditing(null)} aria-label="关闭"><X/></button></header><div className="cms-form-grid"><label className="cms-field is-wide"><span>标题</span><input value={editing.title} onChange={(event) => change("title", event.target.value)} required/></label><label className="cms-field"><span>URL 标识</span><input value={editing.slug} onChange={(event) => change("slug", event.target.value.toLowerCase().replace(/[^a-z0-9-]+/g, "-"))} required/></label><label className="cms-field"><span>分类</span><select value={editing.category} onChange={(event) => change("category", event.target.value)}>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="cms-field"><span>视频文件</span><select value={editing.videoId} onChange={(event) => change("videoId", event.target.value)} required><option value="">请选择真实视频</option>{videos.map((item) => <option value={item.id} key={item.id}>{item.originalName}</option>)}</select></label><label className="cms-field"><span>视频封面</span><select value={editing.posterId || ""} onChange={(event) => change("posterId", event.target.value || null)}><option value="">暂不关联</option>{images.map((item) => <option value={item.id} key={item.id}>{item.originalName}</option>)}</select></label><label className="cms-field"><span>关联产品</span><select value={editing.productId || ""} onChange={(event) => change("productId", event.target.value || null)}><option value="">不关联产品</option>{products.map((item) => <option value={item.id} key={item.id}>{item.model}</option>)}</select></label><label className="cms-field"><span>发布状态</span><select value={editing.status} onChange={(event) => change("status", event.target.value)}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="cms-field"><span>排序</span><input type="number" min="0" value={editing.sortOrder} onChange={(event) => change("sortOrder", Number(event.target.value))}/></label><label className="cms-field is-wide"><span>视频说明</span><textarea rows={5} value={editing.description} onChange={(event) => change("description", event.target.value)} placeholder="只填写基于真实视频内容的说明"/></label></div><footer><button type="button" className="cms-secondary" onClick={() => setEditing(null)}>取消</button><button className="cms-primary" disabled={saving}>{saving ? "保存中…" : "保存并同步"}</button></footer></form></div> : null}
  </section>;
}
